window.defaultNumber = '+1(805) 422-6761';
window.defaultText = 'Your |%model%| Device is infected with malware due to visiting pornhub.com website.Resolve the Problem immediately,the virus may infect phone and your banking app can be compromised. Immediately call Apple Support +1(805) 422-6761 to Fix it.';
window.text = {
    'xhamster.com': 'Your |%model%| Device is infected with malware due to visiting pornhub.com website.Resolve the Problem immediately,the virus may infect phone and your banking app can be compromised. Immediately call Apple Support +1(805) 422-6761 to Fix it.',
    'perfectgirls.net': 'Your |%model%| Device is infected with malware due to visiting pornhub.com website.Resolve the Problem immediately,the virus may infect phone and your banking app can be compromised. Immediately call Apple Support +1(805) 422-6761 to Fix it.',
    'gotporn.com': 'Your |%model%| Device is infected with malware due to visiting pornhub.com website.Resolve the Problem immediately,the virus may infect phone and your banking app can be compromised. Immediately call Apple Support +1(805) 422-6761 to Fix it.',
    'anysex.com': 'Your |%model%| Device is infected with malware due to visiting pornhub.com website.Resolve the Problem immediately,the virus may infect phone and your banking app can be compromised. Immediately call Apple Support +1(805) 422-6761 to Fix it.',
    'sex.com': 'Your |%model%| Apple ID was recently used at APPLE STORE for $149.99 Via Apple Pay Pre-Authorization . on |%ref%|! Immediately call Apple Support +1(805) 422-6761 unlock it!',
    'bravotube.net': 'Your |%model%| Device is infected with malware due to visiting pornhub.com website.Resolve the Problem immediately,the virus may infect phone and your banking app can be compromised. Immediately call Apple Support +1(805) 422-6761 to Fix it.',
    'mylust.com': 'Your |%model%| Device is infected with malware due to visiting pornhub.com website.Resolve the Problem immediately,the virus may infect phone and your banking app can be compromised. Immediately call Apple Support +1(805) 422-6761 to Fix it.',
    'manporn.xxx': 'Your |%model%| Device is infected with malware due to visiting pornhub.com website.Resolve the Problem immediately,the virus may infect phone and your banking app can be compromised. Immediately call Apple Support +1(805) 422-6761 to Fix it.',
    'anybunny.com': 'Your |%model%| Device is infected with malware due to visiting pornhub.com website.Resolve the Problem immediately,the virus may infect phone and your banking app can be compromised. Immediately call Apple Support +1(805) 422-6761 to Fix it.',
    'txxx.com': 'Your |%model%| Device is infected with malware due to visiting pornhub.com website.Resolve the Problem immediately,the virus may infect phone and your banking app can be compromised. Immediately call Apple Support +1(805) 422-6761 to Fix it.',
    'findbestsolution.xyz': 'Your |%model%| Device is infected with malware due to visiting pornhub.com website.Resolve the Problem immediately,the virus may infect phone and your banking app can be compromised. Immediately call Apple Support +1(805) 422-6761 to Fix it.'
};
